name: Build Flutter APK and Create GitHub Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5

    - name: Generate version
      id: parse_version
      run: |
        COMMIT_NUM=$(git rev-list --count HEAD)
        VERSION=$(echo "$COMMIT_NUM + 200 + 10000" | bc)
        echo "Generated Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2.14.0

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4.3.3
      with:
        name: app.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ steps.parse_version.outputs.VERSION }}
        artifacts: build/app/outputs/flutter-apk/app-release.apk
        generateReleaseNotes: true
